version: "3.8"
services:
    db:
      ports:
        - "3306:3306"
    backend:
      volumes:
        - ./backend/.:/app
        - ./backend/node_modules:/app/node_modules
      command: npm run start:debug
    frontend:
      volumes:
        - ./frontend-TS/node_modules:/app/node_modules
