version: "3.8"
services:

  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASS}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
    restart: unless-stopped
    volumes:
      - ./mariaDB/data:/var/lib/mysql:rw

  frontend:
    build: ./frontend-TS
    environment:
      VITE_BACKEND_URL: ${BACKEND_URL}
    depends_on:
      - backend
    restart: always


  backend:
    build: ./backend
    volumes:
      - ./backend/$HTTP_FOLDER:/upload
    environment:
      DB_HOST: ${DB_HOST}
      DB_PASS: ${DB_PASS}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PORT: ${DB_EXPOSE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      SALT: ${SALT}
      CADDY_URL: "${CADDY_HTTP_PROTOCOL}://${CADDY_HOST}"
    depends_on:
      - db
    restart: always
    links:
      - db


  caddy:
    hostname: files
    image: caddy:latest
    restart: always
    environment:
      - CORS_ALLOWED_HOSTS
      - WEBPACK_MODE=development
    volumes:
      - ./backend/$HTTP_FOLDER:/srv
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile


