version: "3.8"
services:

  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASS}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
    restart: unless-stopped
    volumes:
      - ./mariaDB/data:/var/lib/mysql:rw
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend-TS
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: ${BACKEND_URL}
        VITE_CADDY_URL: ${CADDY_HTTP_PROTOCOL}://${CADDY_HOST}
        MODE: ${MODE}
    environment:
      VITE_BACKEND_URL: ${BACKEND_URL}
      VITE_CADDY_URL: ${CADDY_HTTP_PROTOCOL}://${CADDY_HOST}
      MODE: ${MODE}
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

  backend:
    build: ./backend
    volumes:
      - ./backend/$HTTP_FOLDER:/upload
    environment:
      DB_HOST: ${DB_HOST}
      DB_PASS: ${DB_PASS}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PORT: ${DB_EXPOSE_PORT}
      SMTP_DOMAIN: ${SMTP_DOMAIN}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_PORT: ${SMTP_PORT}
      JWT_SECRET: ${JWT_SECRET}
      SALT: ${SALT}
      CADDY_URL: "${CADDY_HTTP_PROTOCOL}://${CADDY_HOST}"
      BACKEND_PORT : ${BACKEND_PORT}
      SWAGGER_RELATIVE_PATH : ${SWAGGER_RELATIVE_PATH}
      SWAGGER_TITLE : ${SWAGGER_TITLE}
      SWAGGER_DESCRIPTION : ${SWAGGER_DESCRIPTION}
      SWAGGER_VERSION : ${SWAGGER_VERSION}
      ADMIN_MAIL: ${ADMIN_MAIL}
      LOG_LEVEL : ${LOG_LEVEL}
    depends_on:
      - db
    restart: ${RESTART}
    links:
      - db
    networks:
      - app-network

  caddy:
    hostname: files
    image: caddy:latest
    restart: ${RESTART}
    environment:
      - CORS_ALLOWED_HOSTS
      - WEBPACK_MODE=development
    volumes:
      - ./backend/$HTTP_FOLDER:/srv
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - app-network

networks:
  app-network:
    driver: bridge




