version: "3.8"
services:

  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASS}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
    restart: unless-stopped
    networks:
      - mirador-multi-user
    volumes:
      - ./mariaDB/data:/var/utils/mysql


  backend:
    build: ./backend
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - mirador-multi-user


  frontend:
    build: ./frontend-TS
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - mirador-multi-user

  proxy:
    restart: always
    build:
      context: ./proxy
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - mirador-multi-user

networks:
  mirador-multi-user:
    driver: bridge
