version: "3.8"
services:

  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASS}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
    restart: unless-stopped
    volumes:
      - ./mariaDB/data:/var/lib/mysql:rw

  frontend:
    build:
      context: ./frontend-TS
      args:
        BACKEND_URL: ${BACKEND_URL}
    environment:
      BACKEND_URL: ${BACKEND_URL}
    depends_on:
      - backend
    restart: unless-stopped


  backend:
    build: ./backend
    environment:
      DB_HOST: ${DB_HOST}
      DB_PASS: ${DB_PASS}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PORT: ${DB_PORT}
      JWT_SECRET: ${JWT_SECRET}
      SALT: ${SALT}
    depends_on:
      - db
    restart: unless-stopped
    links:
      - db
