version: "3.8"
services:

  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASS}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
    restart: unless-stopped
    volumes:
      - ./mariaDB/data:/var/utils/mysql

  frontend:
    build:
      context: ./frontend-TS
      args:
        BACKEND_URL: ${BACKEND_URL}
    environment:
      BACKEND_URL: ${BACKEND_URL}
    depends_on:
      - backend
    restart: unless-stopped


  backend:
    build: ./backend
    depends_on:
      - db
    restart: unless-stopped
    links:
      - db
