version: "3.4"
services:
  httpd:
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.${HTTPD_NAME}.rule=Host(`${HTTPD_HOST}`)"
      - "traefik.http.routers.${HTTPD_NAME}.tls.certresolver=myresolver"
      - "traefik.http.routers.${HTTPD_NAME}.entrypoints=web,websecure"
      - "traefik.http.routers.${HTTPD_NAME}.middlewares=hardening@docker"

  filebrowser:
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.${NAME}.rule=Host(`${HOST}`)"
      - "traefik.http.routers.${NAME}.tls.certresolver=myresolver"
      - "traefik.http.routers.${NAME}.entrypoints=web,websecure"
      - "traefik.http.routers.${NAME}.middlewares=hardening@docker"

networks:
  traefik:
    external: true
